version: '2'

services:
  webapp:
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT}
      - CALLBACK_URL=${CALLBACK_URL}
      - SERVER_PORT=${SERVER_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    image: sudokrew/krew-konsole-app:0.0.0-rc.0
